source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'CognitoYourUserPoolsSample' do
    pod 'AWSCore', '~> 2.4.1'
    pod 'AWSCognitoIdentityProvider', '~> 2.4.1'
end
