source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'PollySample' do
  $awsVersion = '~> 2.12.0'
  pod 'AWSMobileClient', $awsVersion
  pod 'AWSPolly', $awsVersion
end
