source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'S3TransferUtilitySampleSwift' do
  $awsVersion = '~> 2.11.0'
  pod 'AWSMobileClient', $awsVersion
  pod 'AWSS3', $awsVersion
end
