source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'
use_frameworks!

target 'S3TransferUtilitySampleSwift' do
  pod 'AWSAuthCore'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSCognitoIdentityProviderASF'
  pod 'AWSCore'
  pod 'AWSMobileClient'
  pod 'AWSS3'
  
end
