source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'SNS_MobileAnalytics_Sample' do
    pod 'AWSMobileAnalytics', '~> 2.4.1'
    pod 'AWSSNS', '~> 2.4.1'
end
