source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'S3TransferManagerSample' do
    pod 'AWSS3', '~> 2.6.0'

    pod 'ELCImagePickerController'
    pod 'JTSImageViewController'
end
