# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

target 'PinpointSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinpointSample
  pod 'AWSPinpoint', '~> 2.11.1'
  pod 'AWSMobileClient', '~> 2.11.1'
  
  # Tools
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'

end
