source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'CognitoSyncDemo' do
    pod 'AWSCognito', '~> 2.2.0'
    pod 'UICKeyChainStore', '~> 2.0.0'
    pod 'FBSDKLoginKit', '~> 4.6.0'
    pod 'FBSDKCoreKit', '~> 4.6.0'
    pod 'FBSDKShareKit', '~> 4.6.0'
    #pod 'google-plus-ios-sdk'
end
