source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'CognitoYourUserPoolsSample' do
  $awsVersion = '~> 2.10.0'
  pod 'AWSCore', $awsVersion
  pod 'AWSCognitoIdentityProvider', $awsVersion
end
