source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'S3TransferManagerSampleSwift' do
    pod 'AWSS3', '~> 2.4.1'
    pod 'ELCImagePickerController'
    pod 'JTSImageViewController'
end
