source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
target :'Lex-Sample' do
  pod 'JSQMessagesViewController', '~>7.3.4'

  $awsVersion = '~> 2.11.0'
  pod 'AWSLex', $awsVersion
end


